package maturation

// Conversation representa uma conversa entre dois números
// Cada mensagem alterna entre os dois números:
// - Índice par (0, 2, 4...): Número A envia para B
// - Índice ímpar (1, 3, 5...): Número B envia para A
type Conversation []string

// Conversations contém 10 conversas genéricas em português
// para simular interações humanas reais no WhatsApp
var Conversations = []Conversation{
	// Conversa 1: Cumprimento casual
	{ 
		"Oi, tudo bem?",
		"Tudo sim! E você?",
		"Tudo ótimo, obrigado por perguntar!",
		"Que bom! Qualquer coisa estou por aqui.",
		"Valeu! Aliás, como tá o dia aí?",
		"Tá bem corrido, pra falar a verdade.",
		"Imagino, segunda-feira é sempre assim.",
		"Nem me fale. E o seu trabalho?",
		"Tranquilo, hoje tá mais calmo.",
		"Sorte a sua! Queria estar assim.",
		"Logo melhora, respira fundo.",
		"Tô tentando! Já tomou café?",
		"Já sim, duas xícaras.",
		"Nossa, eu preciso de um agora.",
		"Vai lá, dá uma pausa.",
		"Vou mesmo, senão não aguento.",
		"E o projeto novo, saiu?",
		"Ainda não, estamos aguardando aprovação.",
		"Demora mesmo, burocracia é fogo.",
		"Pois é, trava tudo.",
		"Mas vai dar certo, o plano tá bom.",
		"Tomara, trabalhamos muito nisso.",
		"E o chefe, tá pegando no pé?",
		"Hoje até que não, tá de bom humor.",
		"Milagre! Aproveita.",
		"Hahaha, vou aproveitar pra pedir férias.",
		"Boa estratégia! Vai viajar?",
		"Queria ir pra praia, mas tá chovendo.",
		"Verdade, o tempo virou do nada.",
		"Aqui tá caindo um dilúvio.",
		"Aqui só tá nublado por enquanto.",
		"Melhor levar guarda-chuva na saída.",
		"Sempre ando com um na mochila.",
		"Prevenido! É o melhor jeito.",
		"Viu o jogo ontem à noite?",
		"Vi sim! Que sufoco, hein?",
		"Quase tive um ataque no final.",
		"Aquele gol nos acréscimos salvou.",
		"Foi sorte, o time jogou mal.",
		"Concordo, precisam treinar mais defesa.",
		"O próximo jogo vai ser difícil.",
		"Vai ser clássico, né?",
		"Sim, estádio vai estar lotado.",
		"Vou tentar comprar ingresso.",
		"Boa sorte, vai acabar rápido.",
		"Se não der, vejo no bar mesmo.",
		"Também é bom, cerveja gelada.",
		"Falando nisso, vamos marcar um happy hour?",
		"Com certeza! Essa semana?",
		"Pode ser sexta, pra fechar bem.",
		"Sexta é perfeito. Aquele bar novo?",
		"Isso, dizem que o petisco lá é ótimo.",
		"Fechado então. Chamo o pessoal?",
		"Chama sim, quanto mais gente melhor.",
		"Beleza, vou criar um grupo.",
		"Show. Mudando de assunto, viu a série nova?",
		"Aquela de suspense que lançou sexta?",
		"Essa mesma! Maratonou?",
		"Ainda não, vi só o primeiro episódio.",
		"Menino, o final é chocante.",
		"Não me dá spoiler, pelo amor de Deus!",
		"Relaxa, sou um túmulo.",
		"Vou tentar terminar hoje à noite.",
		"Prepara o coração, é tensa.",
		"Adoro série assim, que prende a gente.",
		"Eu também, não consegui dormir depois.",
		"Hahaha, sério? É de terror?",
		"Não, é suspense psicológico.",
		"Ah, esses são os melhores.",
		"Sim. E tá lendo algum livro?",
		"Comecei um de ficção científica.",
		"Sobre o quê?",
		"Viagem no tempo e robôs.",
		"Parece interessante, qual o nome?",
		"Depois te mando a foto da capa.",
		"Manda sim, preciso de indicações.",
		"Minha pilha de leitura só cresce.",
		"A minha também, compro e não leio.",
		"Mal de leitor, né?",
		"Total. A estante tá cheia.",
		"E a dieta? Tá firme?",
		"Rapaz, tá difícil resistir.",
		"Final de semana é complicado.",
		"Comi pizza sábado e hambúrguer domingo.",
		"Nossa, chutou o balde mesmo.",
		"Chutei o balde e a bacia.",
		"Hahaha, acontece. Hoje volta pro foco.",
		"Sim, trouxe salada pro almoço.",
		"Isso aí, equilíbrio é tudo.",
		"Mas tô morrendo de fome já.",
		"Salada não enche muito, né?",
		"Nada, daqui a pouco como uma fruta.",
		"Tá treinando na academia?",
		"Fui hoje de manhã cedo.",
		"Que coragem! Eu só vou à noite.",
		"À noite a preguiça me pega.",
		"Eu prefiro, desestressa do trabalho.",
		"Tem isso também. Mas acordar cedo é duro.",
		"Eu pareço um zumbi de manhã.",
		"Dois. Só funciono depois do café.",
		"Café é vida. O que seria de nós sem ele?",
		"Provavelmente estaríamos dormindo agora.",
		"Fato. Viu a notícia do trânsito?",
		"Não, o que houve?",
		"Acidente na avenida principal, tudo parado.",
		"Vixe, vou ter que pegar um atalho.",
		"Melhor mesmo, o Waze tá tudo vermelho.",
		"Obrigado por avisar, ia ficar preso lá.",
		"Trânsito nessa cidade tá impossível.",
		"Cada dia pior, muito carro na rua.",
		"Tô pensando em comprar uma bike.",
		"É uma boa, economiza e exercita.",
		"O problema é chegar suado.",
		"Tem vestiário no seu prédio?",
		"Tem um chuveiro lá embaixo.",
		"Então resolveu, vai de bike.",
		"Vou pesquisar uns modelos e preços.",
		"Cuidado no trânsito, usa capacete.",
		"Pode deixar, segurança primeiro.",
		"E sua família, todos bem?",
		"Tudo ótimo, minha mãe mandou beijo.",
		"Manda outro pra ela, saudades da tia.",
		"Ela vive perguntando de você.",
		"Vou passar lá qualquer dia pra tomar café.",
		"Passa sim, ela vai fazer bolo.",
		"Bolo de cenoura com chocolate?",
		"O clássico! Ela não falha.",
		"Nossa, agora deu água na boca.",
		"Ela fez um ontem, pena que acabou.",
		"Que maldade falar isso.",
		"Hahaha, na próxima eu guardo um pedaço.",
		"Bom mesmo. E seu cachorro?",
		"O Rex? Tá destruindo tudo.",
		"Ele ainda é filhote?",
		"Já tem um ano, mas age como bebê.",
		"Comeu chinelo de novo?",
		"Dessa vez foi o pé da mesa.",
		"Meu Deus! Prejuízo.",
		"Pois é, mas ele faz aquela cara de coitado.",
		"E a gente perdoa na hora, né?",
		"Não tem como ficar bravo por muito tempo.",
		"Bichinhos são tudo de bom.",
		"São sim, alegram a casa.",
		"Tô querendo adotar um gato.",
		"Adota! Gato é muito independente.",
		"É, eu fico muito tempo fora.",
		"Gato se vira bem sozinho.",
		"Só preciso telar as janelas.",
		"Isso é essencial, não esquece.",
		"Vou ver isso semana que vem.",
		"Depois manda foto se adotar.",
		"Mando sim. Mudando de papo, e as férias?",
		"Só em dezembro, infelizmente.",
		"Longe ainda, hein?",
		"Tô contando os dias no calendário.",
		"Vai passar rápido.",
		"Espero. Preciso desconectar.",
		"Vai pra onde? Decidiu?",
		"Acho que vou pro campo, hotel fazenda.",
		"Delícia! Comer bem e dormir.",
		"Exato, nada de internet.",
		"Duvido você aguentar sem celular.",
		"Vou tentar! Desafio detox.",
		"Eu não aguento um dia.",
		"É vício, a gente precisa tratar.",
		"Verdade. Mas e o computador, arrumou?",
		"Mandei formatar, tava muito lento.",
		"Era vírus?",
		"Acho que não, só HD cheio mesmo.",
		"Colocou um SSD?",
		"Coloquei, dizem que voa.",
		"Muda a vida, liga em segundos.",
		"Tô ansioso pra testar.",
		"Vale cada centavo o investimento.",
		"Bom saber. E seu celular novo?",
		"Câmera incrível, tô tirando foto de tudo.",
		"A bateria dura bem?",
		"Dura o dia todo tranquilo.",
		"O meu tá pedindo socorro já.",
		"Troca logo, aproveita promoção.",
		"Vou esperar a Black Friday.",
		"É, tá perto, vale a pena esperar.",
		"Tomara que tenha desconto real.",
		"Tem que monitorar os preços antes.",
		"Já tô com o site aberto aqui.",
		"Esperto. Olha, preciso te pedir um favor.",
		"Pode falar, o que manda?",
		"Tem aquele contato do fornecedor?",
		"Tenho sim, te mando no zap.",
		"Isso, me salva muito.",
		"Já enviei, confere aí.",
		"Chegou! Valeu demais.",
		"Precisando é só gritar.",
		"Você é dez. E o almoço hoje?",
		"Vou pedir marmita mesmo.",
		"Preguiça de sair?",
		"Muita, e tá chuviscando.",
		"Vou pedir também então.",
		"Pede naquele lugar de massas.",
		"Boa ideia, lasanha hoje.",
		"Lasanha em plena segunda? Corajoso.",
		"Ah, mereço um agrado.",
		"Tá certo. Eu vou de frango grelhado.",
		"Fit como sempre.",
		"Tentando, né? Hahaha.",
		"Escuta, viu o preço da gasolina?",
		"Nem me lembre, chorei no posto.",
		"Tá inviável andar de carro.",
		"Por isso a ideia da bike é séria.",
		"Ou transporte público.",
		"O problema é que lota muito.",
		"Verdade, vai parecendo sardinha.",
		"Vida de adulto não é fácil.",
		"Ninguém avisou que seria assim.",
		"Se soubesse tinha ficado criança.",
		"Bons tempos de só brincar e dormir.",
		"E assistir desenho de manhã.",
		"Nostalgia bateu forte agora.",
		"Pois é. Mas vamos focar no trabalho.",
		"Infelizmente os boletos não param.",
		"Eles chegam todo mês, fiéis.",
		"Mais fiéis que muito namoro.",
		"Hahaha, essa foi boa.",
		"Mas é a pura verdade.",
		"Bom, vou voltar pro relatório aqui.",
		"Vai lá, bom trabalho.",
		"Pra você também, força aí.",
		"Mais tarde a gente se fala.",
		"Me avisa sobre o happy hour.",
		"Pode deixar, vou agitar o povo.",
		"Não esquece de chamar o Bruno",
		"O primo do Jarbas?",
		"Sim, isso mesmo.",
		"Tranquilo, combinado então",
		"Qualquer novidade me grita.",
		"Grito sim. Abraço!",
		"Outro. Se cuida.",
		"Até mais!",
		"Tchau tchau.",
		"Fui!",
		"Valeu!",
	},

	// Conversa 2: Marcando encontro
	{
		"E aí, vamos marcar algo essa semana?",
		"Bora! Que dia você pode?",
		"Quinta ou sexta pra mim tá tranquilo",
		"Sexta então! Te mando o local depois",
		"Fechado. Mas que horas?",
		"Acho que umas 19h tá bom, né?",
		"Por mim beleza, saio do trabalho às 18h.",
		"Perfeito, dá tempo de chegar.",
		"A gente vai comer ou só beber?",
		"Cara, eu tô com uma fome de leão ultimamente.",
		"Hahaha, novidade.",
		"Então bora jantar.",
		"Sushi?",
		"Putz, comi sushi ontem.",
		"Sério? Nem chamou.",
		"Foi de última hora com o pessoal da firma.",
		"Tô zoando. Hambúrguer então?",
		"Pode ser aquele artesanal novo?",
		"Aquele da esquina?",
		"Isso, dizem que é muito bom.",
		"Demorou. A gente vai lá.",
		"E como tão as coisas no trabalho?",
		"Mano, nem me fale.",
		"Tá osso?",
		"Tá uma loucura total.",
		"O chefe tá pegando no pé?",
		"Demais, prazos apertados e tal.",
		"Sei como é.",
		"E o seu projeto novo?",
		"Tá andando, mas devagar.",
		"Melhor devagar do que parado.",
		"Com certeza. Mas tô cansado.",
		"Imagino. Sexta a gente relaxa.",
		"Preciso muito disso.",
		"Vamos pedir uma torre de chopp?",
		"Com certeza vamos.",
		"Ou duas.",
		"Hahaha, calma que eu tenho que dirigir.",
		"Vai de Uber, pô.",
		"É, pensando bem, melhor.",
		"Assim a gente não se preocupa.",
		"Verdade. E a namorada?",
		"Tá bem, mandou um abraço.",
		"Manda outro pra ela.",
		"Ela perguntou quando a gente vai fazer aquele churrasco.",
		"Verdade! Precisamos marcar.",
		"Pois é, faz tempo que prometemos.",
		"Mês que vem sem falta.",
		"Vou cobrar, hein?",
		"Pode cobrar.",
		"E o futebol, parou?",
		"Cara, lesionei o joelho.",
		"Mentira? Jogando?",
		"Não, desci a escada errado.",
		"Kkkkkkkk que vergonha.",
		"Nem me fale, coisa de velho.",
		"Tá precisando se alongar mais.",
		"Tô precisando é de férias.",
		"Quem não tá?",
		"Viu a série nova que saiu?",
		"Aquela de zumbi?",
		"Isso, The Last of Us.",
		"Vi o primeiro episódio só.",
		"É boa demais, tem que ver.",
		"Vou tentar ver fds.",
		"Não vai se arrepender.",
		"Mas e aí, viu o Lucas?",
		"Encontrei ele no mercado esses dias.",
		"Ele tá bem?",
		"Tá sim, vai ser pai.",
		"Caraca! Sério?",
		"Sério, a esposa tá de 3 meses.",
		"Que massa, não sabia.",
		"Pois é, o tempo voa.",
		"A gente tá ficando velho.",
		"Fala por você.",
		"Hahaha, aceita que dói menos.",
		"Jamais.",
		"Escuta, voltando a sexta.",
		"Diga.",
		"Posso levar um amigo?",
		"Quem?",
		"O Pedro, do colégio.",
		"Claro! Faz anos que não vejo ele.",
		"Ele tá na cidade de passagem.",
		"Show, leva ele sim.",
		"Ele vai curtir te ver.",
		"A gente tem muita história.",
		"Vou avisar ele então.",
		"Beleza.",
		"Ele tá trabalhando com TI agora também.",
		"Sério? Mundo pequeno.",
		"Pois é, vai ter assunto.",
		"Vou levar meu notebook pra ele arrumar então kkk.",
		"Folgado.",
		"Sempre.",
		"Mas falando nisso, meu PC pifou.",
		"O que deu?",
		"Tela azul da morte.",
		"Vish, isso é ruim.",
		"Acho que foi a memória RAM.",
		"Tem que testar.",
		"Vou levar na assistência amanhã.",
		"Melhor coisa que faz.",
		"Não posso ficar sem PC.",
		"Eu sei, vício.",
		"É trabalho, respeita.",
		"Sei, sei. Trabalho no LoL.",
		"Hahaha, também.",
		"Sabia.",
		"Mas parei um pouco, tô sem tempo.",
		"Eu também, vida adulta é triste.",
		"Boleto chega pra todo mundo.",
		"Triste realidade.",
		"Ei, viu o preço da gasolina?",
		"Nem me lembre.",
		"Tá absurdo.",
		"Eu tô andando mais a pé.",
		"Saudável e econômico.",
		"Exato.",
		"E aquele curso que você ia fazer?",
		"De inglês?",
		"Isso.",
		"Comecei mês passado.",
		"E tá curtindo?",
		"Tô sim, o professor é bom.",
		"Online ou presencial?",
		"Online, mais prático.",
		"Boa. Eu preciso melhorar meu inglês.",
		"Faz lá onde eu faço.",
		"Depois me passa o link.",
		"Mando sim.",
		"Valeu.",
		"E sua mãe, como tá?",
		"Tá ótima, viajando.",
		"Que chique. Pra onde?",
		"Foi pra praia com as amigas.",
		"Errada não tá.",
		"Queria eu estar lá.",
		"Todos nós.",
		"Mas aqui tá calor também.",
		"Calor insuportável.",
		"Ar condicionado não tá dando conta.",
		"Nem o meu ventilador.",
		"Tá previsão de chuva pra sexta?",
		"Acho que não, espero que não.",
		"Se chover a gente vai de Uber mesmo.",
		"Sim, sem estresse.",
		"Aquele lugar tem área coberta?",
		"Tem sim, lá dentro é climatizado.",
		"Ah, então suave.",
		"Não gosto de passar calor comendo.",
		"Ninguém merece.",
		"Vou pedir aquela batata com cheddar.",
		"Nossa, lá é muito boa.",
		"Já tô com água na boca.",
		"Eu também.",
		"Foco na dieta até sexta.",
		"Hahaha, dieta de segunda a quinta.",
		"É o equilíbrio.",
		"Exatamente.",
		"Vou ver se termino aquele relatório hoje.",
		"Pra ficar livre amanhã?",
		"Isso, odeio deixar pendência.",
		"Te entendo.",
		"Vou tentar sair mais cedo na sexta.",
		"Se conseguir, avisa.",
		"Aviso sim.",
		"Aí a gente chega lá e pega mesa boa.",
		"Isso, porque lá lota.",
		"Lota mesmo.",
		"Se o Pedro for, precisa de lugar pra 3.",
		"Tranquilo, a gente acha.",
		"Qualquer coisa senta no balcão.",
		"Também serve.",
		"O importante é a cerveja gelada.",
		"E o papo em dia.",
		"Com certeza.",
		"Tô precisando desabafar umas coisas.",
		"Pode falar, sou todo ouvidos.",
		"Lá a gente conversa melhor.",
		"Fechado.",
		"Mas não é nada grave não.",
		"Menos mal.",
		"Coisa da vida.",
		"Sempre é.",
		"E o carro, trocou?",
		"Ainda não, tô pesquisando.",
		"Tá caro demais carro hoje em dia.",
		"Sem condições.",
		"Vou ficar com o meu velhinho mesmo.",
		"Tá rodando, tá valendo.",
		"É isso aí.",
		"Manutenção tá em dia?",
		"Mais ou menos kkk.",
		"Cuidado hein.",
		"Vou ver isso mês que vem.",
		"Não deixa passar.",
		"Pode deixar, pai.",
		"Tô só avisando.",
		"Eu sei, valeu a preocupação.",
		"Tamo junto.",
		"Sempre.",
		"Vou ter que sair aqui rapidinho.",
		"Reunião?",
		"É, cliente ligando.",
		"Vai lá, bom trabalho.",
		"Valeu, pra você também.",
		"Depois a gente se fala.",
		"Beleza.",
		"Não esquece de me mandar o local exato.",
		"Pode deixar, mando a localização.",
		"Isso, manda no Maps.",
		"Beleza.",
		"Até mais.",
		"Até.",
		"Voltei.",
		"Eita, foi rápido.",
		"Foi só pra tirar dúvida.",
		"Menos mal.",
		"Cara, lembrei de uma coisa.",
		"O quê?",
		"Você ainda tem aquele livro?",
		"Qual deles?",
		"O do Senhor dos Anéis.",
		"Tenho sim, por quê?",
		"Me empresta depois?",
		"Claro, levo na sexta.",
		"Show, quero reler.",
		"Corajoso.",
		"Kkkk é bom demais.",
		"É sim, clássico.",
		"Vou levar pra você então.",
		"Valeu mesmo.",
		"Tranquilo.",
		"Agora vou almoçar.",
		"Bom almoço.",
		"Vai comer o quê?",
		"Marmita de ontem.",
		"Clássico também.",
		"Economia né.",
	},

	// Conversa 3: Sobre o trabalho
	{
		"Como tá o trabalho?",
		"Corrido, mas tudo sob controle. E o seu?",
		"Também bastante coisa, mas dando conta",
		"É assim mesmo, força aí!",
		"O prazo da entrega tá chegando, né?",
		"Sim, faltam só dois dias.",
		"Nossa, vai ter que fazer hora extra?",
		"Provavelmente, mas espero que não muito.",
		"Entendo, semana passada fui até tarde também.",
		"É cansativo, mas faz parte.",
		"E aquele bug, resolveu?",
		"Ainda não, tá dando uma dor de cabeça.",
		"Imagino, código legado é complicado.",
		"Nem me fale, ninguém entende a lógica daquilo.",
		"Precisando de ajuda, dá um toque.",
		"Valeu, se apertar eu te chamo.",
		"E o chefe, tá pegando no pé?",
		"Hoje tá tranquilo, por milagre.",
		"O meu tá pedindo relatório toda hora.",
		"Isso quebra o ritmo demais.",
		"Pois é, paro de programar pra preencher planilha.",
		"Produtividade vai lá pra baixo.",
		"Mas enfim, bora tomar um café?",
		"Bora, tô precisando acordar.",
		"Aquele expresso duplo pra dar vida.",
		"Com certeza, sem açúcar pra bater forte.",
		"Viu o e-mail do RH?",
		"Vi sim, sobre o feriado?",
		"Isso, vão emendar, graças a Deus.",
		"Nossa, eu tava precisando dessa folga.",
		"Já tem planos pra viajar?",
		"Ainda não, talvez só descansar em casa.",
		"Eu vou pra praia se não chover.",
		"Tomara que faça sol então.",
		"E a família, tudo certo?",
		"Tudo ótimo, meu filho começou a andar.",
		"Que legal! Fase boa essa.",
		"Boa e perigosa, mexe em tudo.",
		"Hahaha, tem que ficar de olho.",
		"Verdade. E seus pais?",
		"Estão bem, visitaram a gente domingo.",
		"Bom demais reunir a família.",
		"Sim, churrasco e conversa fora.",
		"Falando em comida, tá com fome?",
		"Começando a bater aquela fome sim.",
		"O que vamos almoçar hoje?",
		"Pensei naquele quilo aqui perto.",
		"Pode ser, a lasanha de lá é boa.",
		"Fechado então, 12:30?",
		"Combinado. Mas antes preciso terminar isso aqui.",
		"O que você tá fazendo agora?",
		"Ajustando o layout da home.",
		"Ah, o cliente pediu alteração?",
		"Pediu pra mudar a cor do botão.",
		"Sério? De novo?",
		"Sim, agora quer azul marinho.",
		"Gosto de cliente não se discute, né.",
		"Pois é, o cliente tem sempre razão.",
		"Mesmo quando tá errado.",
		"Exatamente, hahaha.",
		"Viu a série nova que estreou?",
		"Ainda não, é boa?",
		"Cara, é sensacional, assisti 3 episódios ontem.",
		"Vou colocar na lista pra ver fds.",
		"Faz isso, o final do primeiro é chocante.",
		"Sem spoilers, por favor!",
		"Tranquilo, não vou estragar a surpresa.",
		"Você joga videogame?",
		"Jogo sim, peguei um PS5 recentemente.",
		"Que massa! Tá jogando o quê?",
		"O novo Spider-Man, gráficos incríveis.",
		"Dizem que a história é muito boa mesmo.",
		"É sim, vale cada centavo.",
		"Eu sou mais do PC, jogo de estratégia.",
		"Civilization? Age of Empires?",
		"Isso, adoro perder horas no Civ.",
		"Haja paciência, uma partida dura dias.",
		"Essa é a graça, construir um império.",
		"Cada um com seu vício, né?",
		"Com certeza. Voltando ao trabalho...",
		"É, o dever chama.",
		"Recebeu o convite da reunião?",
		"Recebi, às 15h, né?",
		"Isso, reunião de alinhamento.",
		"Lá vem mais demanda.",
		"Espero que seja rápida.",
		"Duvido, o gerente fala pelos cotovelos.",
		"Vou levar meu caderno pra desenhar.",
		"Hahaha, boa estratégia pra não dormir.",
		"Você viu a atualização do sistema?",
		"Vi, mudou todos os ícones.",
		"Ficou meio confuso, não achei nada.",
		"Questão de costume, logo a gente adapta.",
		"Eu preferia o antigo, era mais limpo.",
		"Eu curti o modo noturno, cansa menos a vista.",
		"Ah, isso é verdade, ajuda muito.",
		"Sua internet tá boa hoje?",
		"Tá oscilando um pouco, e aí?",
		"Aqui caiu duas vezes de manhã.",
		"Complicado depender da operadora.",
		"Se cair de novo vou rotear o 4G.",
		"É o jeito pra não ficar parado.",
		"E aquele curso que você ia fazer?",
		"De Python? Comecei semana passada.",
		"E aí, tá curtindo?",
		"Tô sim, a didática é muito boa.",
		"Legal, investir em conhecimento é sempre bom.",
		"Pois é, o mercado pede atualização.",
		"Verdade, tecnologia muda todo dia.",
		"Quando terminar me passa o link?",
		"Passo sim, pode deixar.",
		"Olha só, começou a chover.",
		"Nossa, caiu o mundo lá fora.",
		"Espero que pare até a hora de ir embora.",
		"Se não o trânsito vai travar tudo.",
		"Já é caótico normalmente, com chuva então...",
		"Nem me lembre, levo uma hora pra chegar.",
		"Você vem de carro ou ônibus?",
		"Venho de carro, mas pego muito engarrafamento.",
		"Eu venho de metrô, é cheio mas é rápido.",
		"Vantagem de não pegar semáforo.",
		"Exato, vou lendo um livro no caminho.",
		"Qual livro tá lendo agora?",
		"Uma biografia do Steve Jobs.",
		"Clássica, já li faz tempo.",
		"Muito inspiradora, o cara era visionário.",
		"E meio difícil de lidar também.",
		"Gênios geralmente são complicados.",
		"Fato. E aí, conseguiu enviar o arquivo?",
		"Tô tentando, mas o upload tá lento.",
		"Deve ser a rede sobrecarregada.",
		"Vou tentar compactar pra ver se vai.",
		"Boa ideia, zipa tudo.",
		"Pronto, agora foi. Ufa!",
		"Menos um problema.",
		"Agora falta só responder os tickets.",
		"Tem muitos pendentes?",
		"Uns 15, a maioria dúvida simples.",
		"Mata logo isso pra ficar livre.",
		"Vou fazer um mutirão aqui agora.",
		"Se precisar que eu assuma algum, avisa.",
		"Tranquilo, dou conta, valeu.",
		"O ar condicionado tá muito frio aí?",
		"Tá congelando, parece o Alasca.",
		"Vou lá aumentar a temperatura um pouco.",
		"Faz esse favor, tô quase de casaco.",
		"Pronto, coloquei em 23 graus.",
		"Melhorou, tava insuportável.",
		"Sempre tem briga pelo controle do ar.",
		"Sempre, uns com calor, outros com frio.",
		"A convivência em escritório é uma arte.",
		"Hahaha, pura verdade.",
		"Lembra do Pedro, do financeiro?",
		"Lembro sim, o que tem ele?",
		"Vai sair da empresa mês que vem.",
		"Mentira? Ele tava aqui há anos.",
		"Pois é, recebeu uma proposta melhor.",
		"Que bom pra ele, fará falta.",
		"Gente boa demais, sempre ajudava.",
		"Vamos fazer uma despedida?",
		"Com certeza, um happy hour.",
		"Vou organizar no grupo do WhatsApp.",
		"Isso, vê um barzinho legal.",
		"Pode deixar, vou ver aquele do centro.",
		"Aquele que tem música ao vivo?",
		"Esse mesmo, é animado.",
		"Show, tô dentro.",
		"Mudando de assunto, viu o dólar?",
		"Nem vejo pra não chorar.",
		"Subiu de novo, tá impossível comprar hardware.",
		"Eu queria trocar minha placa de vídeo.",
		"Vai ter que esperar baixar um pouco.",
		"Ou parcelar em 12 vezes.",
		"Juros comendo solto, cuidado.",
		"É, vou segurar a onda com a velha mesmo.",
		"Melhor, economiza pra viagem.",
		"Ah, a viagem do fim do ano!",
		"Já decidiu pra onde vai?",
		"Tô pensando em ir pro Sul.",
		"Gramado? É bonito lá.",
		"Isso, ver o Natal Luz.",
		"Leva casaco que lá é frio mesmo no verão.",
		"Vou preparado. E você, vai ficar por aqui?",
		"Vou visitar meus avós no interior.",
		"Interior é bom pra relaxar a mente.",
		"Comida de vó não tem igual.",
		"Engordar uns 3 quilos brincando.",
		"Essa é a meta, hahaha.",
		"Olha a hora, a reunião vai começar.",
		"Vixe, verdade, vamos lá.",
		"Leva a caneta.",
		"Tô levando. Sorte pra nós.",
		"Depois me conta o que decidiram.",
		"Pode deixar, te passo o resumo.",
		"Beleza",
		"E aí, como foi a reunião?",
		"Longa e cansativa, como previsto.",
		"Decidiram algo importante?",
		"Mudaram o cronograma do projeto B.",
		"Adiaram a entrega?",
		"Sim, ganhamo mais duas semanas.",
		"Ufa, uma notícia boa pelo menos.",
		"Sim, dá pra respirar um pouco.",
		"Vou avisar a equipe então.",
		"Avisa sim, vão ficar felizes.",
		"Tô morrendo de sede.",
		"A água do bebedouro acabou.",
		"Sério? Que azar.",
		"Tem que pedir pro rapaz trocar o galão.",
		"Vou lá na copa ver se tem suco.",
		"Traz um copo pra mim?",
		"Trago, de laranja ou uva?",
		"Uva, por favor.",
		"Beleza, já volto.",
		"Vai lá.",
		"Tá aqui seu suco.",
		"Valeu demais, salvou.",
		"Falta muito pra acabar seu dia?",
		"Só mais uns 40 minutos.",
		"O meu também, contagem regressiva.",
		"Hoje rendeu, hein?",
		"Rendeu, fizemos bastante coisa.",
		"Amanhã a gente foca nos testes.",
		"Isso, deixar tudo redondo.",
		"Tem aquele deploy pra sexta-feira.",
		"Sexta é dia perigoso pra deploy.",
		"Lei de Murphy, se der erro...",
		"Fim de semana programando.",
		"Nem brinca, vira essa boca pra lá.",
		"Vamos revisar tudo duas vezes.",
		"Três vezes se for preciso.",
		"Hahaha, seguro morreu de velho.",
		"O computador tá começando a travar.",
		"Reinicia, as vezes resolve.",
		"Vou fazer isso, tá com muita aba aberta.",
		"O navegador consome toda a memória.",
		"Preciso de mais RAM urgente.",
		"Pede pro suporte técnico.",
		"Já pedi, tá na fila de espera.",
		"Burocracia é fogo.",
		"Enquanto isso a gente sofre.",
	},

	// Conversa 4: Agradecimento
	{
		"Muito obrigado pela ajuda de ontem!",
		"Imagina, foi um prazer ajudar",
		"Você salvou meu dia, sério mesmo",
		"Pode contar comigo sempre que precisar",
		"Eu estava travado naquilo há horas",
		"Eu percebi que você estava meio estressado",
		"Estressado é pouco, eu estava surtando",
		"Hahaha imagino, aquele relatório era chato",
		"Chato e complicado demais",
		"Mas no fim deu tudo certo",
		"Sim, enviei no prazo exato",
		"Que bom! O chefe falou algo?",
		"Ele elogiou, acredita?",
		"Mentira! Sério?",
		"Sério! Disse que a formatação estava ótima",
		"Aí sim, ponto pra gente",
		"Tudo graças à sua dica do Excel",
		"Aquela fórmula salva vidas",
		"Eu nunca ia pensar naquilo sozinho",
		"Vivendo e aprendendo, né?",
		"Com certeza. Te devo uma",
		"Que nada, relaxa",
		"Faço questão, vamos almoçar semana que vem",
		"Opa, se tem comida eu aceito",
		"Hahaha combinado então",
		"Pode ser na terça?",
		"Terça feira é tranquilo pra mim",
		"Beleza, terça então",
		"Aquele restaurante novo?",
		"Isso, o de massas",
		"Dizem que o macarrão lá é top",
		"Também ouvi falar muito bem",
		"Fechado então",
		"Maravilha",
		"E como estão as coisas por aí?",
		"Correrria de sempre",
		"Imagino, fim de mês é osso",
		"Nem me fale, tô cheio de planilha",
		"Se precisar de ajuda, avisa",
		"Pode deixar, mas acho que dou conta",
		"Qualquer coisa grita",
		"Hahaha beleza",
		"E o projeto novo?",
		"Tá caminhando, devagar mas vai",
		"Tem prazo pra quando?",
		"Mês que vem só",
		"Ah, então tá suave",
		"Mais ou menos, tem muita coisa pra fazer",
		"Mas você desenrola rápido",
		"Tento né, fazer o que",
		"Vai dar certo",
		"Tomara",
		"E o fim de semana? Vai fazer o que?",
		"Cara, acho que vou só dormir",
		"Hahaha tá precisando?",
		"Muito! Tô exausto",
		"Eu também, semana foi pesada",
		"Vou maratonar alguma série",
		"Boa! Tem alguma em vista?",
		"Tava pensando em rever The Office",
		"Clássica! Nunca enjoa",
		"Exato, bom pra rir um pouco",
		"Eu comecei uma nova ontem",
		"Qual?",
		"Aquela de ficção na Netflix",
		"Ah, tô ligado qual é",
		"É boa mesmo?",
		"Cara, eu tô curtindo bastante",
		"Vou colocar na lista então",
		"Coloca sim, vale a pena",
		"E sua família, tudo bem?",
		"Tudo ótimo graças a Deus",
		"E a sua?",
		"Tudo paz também",
		"Meu irmão vai casar mês que vem",
		"Mentira? Que notícia boa!",
		"Pois é, correria com os preparativos",
		"Imagino a loucura que deve tá",
		"Minha mãe tá doida já",
		"Mães sempre ficam né hahaha",
		"Ficam preocupadas com tudo",
		"Mas no fim a festa é linda",
		"Sim, vai ser legal",
		"Vai ter festa grande?",
		"Mais ou menos, só família e amigos",
		"Melhor assim, mais íntimo",
		"Também acho",
		"E você, novidades?",
		"Ah, troquei de carro finalmente",
		"Sério? Pegou qual?",
		"Um hatch, preto",
		"Show de bola! Zero?",
		"Seminovo, mas tá inteiro",
		"Que massa, parabéns!",
		"Valeu! Tava precisando",
		"O antigo tava dando dor de cabeça?",
		"Nossa, muita oficina",
		"Ninguém merece viver na oficina",
		"Pois é, gastei uma nota",
		"Agora vai ficar tranquilo",
		"Espero que sim",
		"Vai viajar pra estrear?",
		"Tô querendo ir pra praia",
		"Boa pedida",
		"Se fizer sol vai ser top",
		"A previsão diz que vai fazer",
		"Então fechou",
		"Chama a galera",
		"Vou ver quem anima",
		"Se eu não fosse dormir, eu ia",
		"Hahaha prioridades né",
		"Exato, meu sono é sagrado",
		"Te entendo perfeitamente",
		"Mas na próxima eu vou",
		"Combinado",
		"E o futebol, tem jogado?",
		"Parei um pouco, machuquei o joelho",
		"Putz, sério? Nada grave né?",
		"Não, só uma torção leve",
		"Melhoras aí mano",
		"Valeu, já tô fazendo gelo",
		"Logo tá novo",
		"Espero, tô sentindo falta da pelada",
		"Faz falta mesmo o exercício",
		"E a resenha depois também",
		"Com certeza, é a melhor parte",
		"Hahaha verdade",
		"Mas e aí, voltando ao trabalho",
		"Lá vem...",
		"Hahaha desculpa cortar o barato",
		"Tranquilo, o que manda?",
		"Você tem o contato do fornecedor?",
		"Tenho sim, o de TI?",
		"Isso, o que arruma as impressoras",
		"Vou te passar aqui",
		"Beleza, a minha pifou hoje",
		"Nossa, que azar",
		"Pois é, bem na hora de imprimir",
		"Clássico de impressora",
		"Elas sentem o medo da gente",
		"Hahaha total!",
		"Espera aí que vou achar o número",
		"Tranquilo, tô no aguardo",
		"Achei, vou mandar",
		"Manda aí",
		"[Contato enviado]",
		"Show, valeu demais",
		"Ele atende rápido geralmente",
		"Vou ligar agora mesmo",
		"Fala que eu indiquei",
		"Pode deixar, peço desconto",
		"Isso, chora um desconto lá",
		"Sempre bom economizar",
		"Com certeza",
		"Cara, viu o jogo ontem?",
		"Vi só os melhores momentos",
		"Foi jogaço hein",
		"O goleiro catou muito",
		"Inacreditável aquela defesa",
		"Salvou o time",
		"Se não fosse ele, era goleada",
		"Concordo plenamente",
		"Próximo jogo vai ser tenso",
		"Vai ser clássico né?",
		"Sim, vai pegar fogo",
		"Vou tentar assistir ao vivo",
		"Eu também, não perco",
		"Vamos marcar de ver qualquer dia",
		"Bora sim, churrasco e jogo",
		"Combinação perfeita",
		"Já tá marcado mentalmente",
		"Hahaha fechado",
		"E aquele curso que você ia fazer?",
		"Comecei semana passada",
		"E aí? Tá curtindo?",
		"Cara, é bem puxado",
		"Mas o conteúdo é bom?",
		"Excelente, tô aprendendo muito",
		"Isso que importa",
		"Vai agregar muito no currículo",
		"Com certeza, é uma área boa",
		"Investimento no futuro",
		"Exatamente meu pensamento",
		"Boa sorte nas provas",
		"Valeu, vou precisar",
		"Nada, você tira de letra",
		"Tomara viu",
		"Preciso estudar inglês também",
		"Ah, inglês é fundamental",
		"Tô meio enferrujado",
		"Assiste filme sem legenda",
		"Tô tentando fazer isso",
		"Ajuda muito no ouvido",
		"Verdade, vou insistir nisso",
		"É questão de prática",
		"Pois é",
		"Bom, vou nessa que o dever chama",
		"Vai lá, bom trabalho",
		"Pra você também",
		"Depois a gente se fala",
		"Beleza, qualquer coisa chama",
		"Pode deixar",
		"Não esquece do almoço",
		"Tá anotado, terça-feira",
		"Isso aí",
		"Abraço mano",
		"Abraço, fica com Deus",
		"Amém, você também",
		"Até mais",
		"Até",
		"Ah, antes que eu esqueça",
		"Opa, fala",
		"Trouxe aquele livro que te emprestei?",
		"Putz! Sabia que tava esquecendo algo",
		"Hahaha tranquilo",
		"Tá na minha mochila, esqueci de tirar",
		"Sem problemas",
		"Te entrego na terça então",
		"Fechou, sem pressa",
		"Já leu tudo?",
		"Li sim, muito bom",
		"Final surpreendente né?",
		"Demais, não esperava aquilo",
		"Eu fiquei chocado quando li",
		"O autor é gênio",
		"Eu gosto é daquele Jarbas que escreve romance",
		"Sim, ele é muito bom",
		"Demais, melhor que ele só alyrio",
		"Esse não conheço, ele escreveu o que?",
		"Revolução dos machados, conhece?",
		"Ah sim, já ouvi falar um pouco",
		"É muito bom, recomendo",
		"Bom tamebém é aquele akira toriyama",
		"Vou procurar outros dele",
		"Recomendo, tem vários bons",
		"Beleza, vou pesquisar",
		"Agora fui mesmo",
		"Vai lá, tchau",
		"Falou",
		"👋",
		"👍"
	},

	// Conversa 5: Fim de semana
	{
		"Curtiu o fim de semana?",
		"Demais! Descansei bastante. E você?",
		"Também, aproveitei pra ficar em casa",
		"Às vezes é o que a gente precisa mesmo",
		"Com certeza, maratonei uma série nova",
		"Sério? Qual?",
		"Aquela de suspense que todo mundo tá falando",
		"Ah, sei qual é! É boa mesmo?",
		"Cara, é viciante, não conseguia parar",
		"Tô precisando de algo assim pra ver",
		"Assiste, você vai curtir",
		"Quantos episódios são?",
		"São uns 8 ou 10, é rapidinho",
		"Beleza, vou colocar na lista",
		"E você, fez o que de bom?",
		"Eu cozinhei bastante, acredita?",
		"Mentira! Virou chef agora?",
		"Hahaha quem dera, só inventei moda",
		"Fez o que? Lasanha?",
		"Fiz um risoto, ficou até que bom",
		"Nossa, chique hein",
		"Que nada, segui tutorial do YouTube",
		"O importante é ficar gostoso",
		"Sobrou pro almoço de hoje?",
		"Pior que não, comi tudo hahaha",
		"Hahaha sinal que tava bom mesmo",
		"Tava sim, modéstia à parte",
		"Falando em comida, e o almoço amanhã?",
		"Verdade! Vamos naquele lugar de sempre?",
		"Pode ser, tô com desejo de comer lá",
		"Fechado então, meio-dia?",
		"Meio-dia e quinze, pra garantir",
		"Beleza, te espero na frente",
		"E o trabalho, como tá hoje?",
		"Nossa, nem me fale",
		"Tá tenso aí também?",
		"Segunda-feira brava, muito e-mail",
		"Aqui também, o chefe tá daquele jeito",
		"Ninguém merece chefe mal humorado",
		"Pois é, tô só na base do café",
		"Eu já tomei uns três hoje",
		"Cuidado pra não ter taquicardia",
		"Hahaha relaxa, sou acostumado",
		"Viu que o Marcos vai sair?",
		"Sério? Não tava sabendo",
		"Pois é, pediu demissão hoje cedo",
		"Caramba, pra onde ele vai?",
		"Diz que arrumou uma vaga remota",
		"Que sonho, trabalhar de casa",
		"Nem fala, inveja branca dele",
		"Quem sabe a nossa hora não chega",
		"Deus te ouça, amigo",
		"Mas ele mandou bem, merece",
		"Sim, ele é muito competente",
		"Vai fazer falta na equipe",
		"Com certeza, ele resolvia tudo",
		"Agora vai sobrar pra gente",
		"Vira essa boca pra lá",
		"Hahaha tô sendo realista",
		"Infelizmente você tem razão",
		"Mudando de assunto, viu o tempo?",
		"Tá maluco esse tempo, né?",
		"De manhã frio, agora um calorão",
		"Não sei com que roupa eu saio",
		"Eu vim de casaco e me arrependi",
		"Eu trouxe guarda-chuva por via das dúvidas",
		"Fez bem, do jeito que tá...",
		"Previsão disse que chove tarde",
		"Espero que espere eu chegar em casa",
		"Também, odeio pegar chuva no ônibus",
		"É o caos, tudo para",
		"Trânsito fica impossível",
		"Total. Ah, lembrei de uma coisa",
		"Diga lá",
		"Você tem o contato daquele mecânico?",
		"Tenho sim, o Zé?",
		"Isso, meu carro tá fazendo um barulho",
		"Ixi, barulho nunca é bom",
		"Pois é, tô com medo de ser caro",
		"Leva lá, ele é honesto",
		"Me passa o número depois?",
		"Passo sim, vou procurar aqui",
		"Valeu demais",
		"Mas e as novidades, tem mais?",
		"Cara, comprei um celular novo",
		"Mentira! Qual modelo?",
		"Peguei aquele lançamento da maçã",
		"Nossa, ostentação pura",
		"Que nada, parcelei em mil vezes",
		"Hahaha quem nunca",
		"Mas a câmera é absurda",
		"Imagino, as fotos ficam profissionais",
		"Sim, testei no fim de semana",
		"Postou alguma? Nem vi",
		"Ainda não, vou editar primeiro",
		"Ah, todo misterioso",
		"Tem que caprichar no feed né",
		"Tá certo, blogueiro",
		"Hahaha para com isso",
		"E jogo, tem jogado algo?",
		"Voltei a jogar aquele de tiro",
		"Sério? Aquele antigo?",
		"Ele mesmo, lançaram mapa novo",
		"Que massa, preciso baixar de novo",
		"Bora jogar hoje à noite?",
		"Hoje não dá, tenho compromisso",
		"Vai sair?",
		"Vou jantar na casa da minha tia",
		"Ah, entendi. Aniversário?",
		"Não, só visita mesmo",
		"Legal, manda um abraço pra ela",
		"Pode deixar, ela sempre pergunta de você",
		"Ela é muito gente boa",
		"É sim, faz um bolo incrível",
		"Nossa, aquele de cenoura?",
		"Esse mesmo, com cobertura de chocolate",
		"Agora me deu fome",
		"Hahaha desculpa",
		"Traz um pedaço pra mim",
		"Se sobrar, eu levo amanhã",
		"Duvido que sobre",
		"É, lá em casa o povo ataca",
		"Com razão, é bom demais",
		"Vou tentar esconder um pedaço",
		"Isso, esconde na mochila",
		"Hahaha pode deixar",
		"E a viagem de fim de ano?",
		"Ainda tô decidindo, e você?",
		"Tô querendo ir pra praia",
		"Praia é sempre bom, mas lota",
		"Verdade, tem que ter paciência",
		"Tô pensando em ir pro interior",
		"Sossego, né? Boa ideia",
		"Alugar um sítio, piscina...",
		"Nossa, perfeito",
		"Se quiser ir junto, cabe gente",
		"Opa, vou considerar hein",
		"Vê aí e me fala",
		"Quanto ficaria mais ou menos?",
		"Barato, dividindo por pessoa",
		"Me manda os detalhes depois",
		"Mando sim, tô vendo as datas",
		"Beleza. Seria top",
		"Seria mesmo, churrasco todo dia",
		"E piscina o dia todo",
		"Vida de rei",
		"Merecemos, né?",
		"Muito! Trabalhamos pra isso",
		"Falando em trabalho, chegou e-mail",
		"Lá vem bomba?",
		"Acho que não, é convite",
		"Convite de quê?",
		"Festa da empresa",
		"Ah é, já é época disso",
		"Vai ser naquele salão chique",
		"Sério? Capricharam esse ano",
		"Parece que sim, vai ter banda",
		"Aí vi vantagem",
		"Open bar?",
		"Diz aqui que sim",
		"Então eu vou com certeza",
		"Hahaha interesseiro",
		"Ué, tem que aproveitar",
		"Tá certo, vamos combinar de ir",
		"Podemos ir de Uber juntos",
		"Boa, racha a corrida",
		"E a gente pode beber tranquilo",
		"Exato, sem preocupação com direção",
		"Que dia vai ser?",
		"Dia 15, uma sexta",
		"Perfeito, dá pra recuperar no sábado",
		"Vamos precisar de recuperação mesmo",
		"Já tô até vendo o estrago",
		"Hahaha vai ser lendário",
		"Tomara que a comida seja boa",
		"Geralmente é salgadinho, né?",
		"Ah, eu gosto de coxinha",
		"Coxinha é vida",
		"Se tiver bolinha de queijo então...",
		"Nossa, pare, tô com fome de novo",
		"Hahaha tá difícil hoje",
		"Falta muito pro almoço?",
		"Ainda falta uma hora",
		"Tristeza. Vou comer uma bolacha",
		"Me dá uma também?",
		"Passa aqui na minha mesa",
		"Tô indo aí",
		"Traz aquele relatório também",
		"Ah não, lá vem você com trabalho",
		"Ué, aproveita a viagem",
		"Tá bom, tá bom",
		"Tô brincando, só vem comer",
		"Ufa, susto",
		"Mas sério, preciso falar contigo",
		"Sobre o quê?",
		"Aquele projeto do cliente novo",
		"Deu problema?",
		"Não, só um ajuste no prazo",
		"Ah, menos mal",
		"Eles querem adiantar",
		"Adiantar? Estão malucos?",
		"Pois é, querem pra quinta",
		"Impossível, não dá tempo",
		"Eu falei isso, mas insistiram",
		"Vou ter que fazer hora extra?",
		"Provavelmente nós dois",
		"Putz, lá se vai minha academia",
		"Relaxa, a gente pede pizza",
		"Pizza paga pela firma?",
		"Claro, é o mínimo",
		"Então tá menos pior",
		"Qual sabor a gente pede?",
		"Calabresa e Portuguesa, clássicas",
		"Fechado. Odeio inventar moda em pizza",
		"Pizza doce nem pensar né?",
		"Ah, uma de chocolate vai bem",
		"Tá, uma brotinho de sobremesa",
		"Isso, pra fechar com chave de ouro",
		"Beleza, resolvido então",
		"Foco no trabalho agora",
		"Sim, bora produzir",
		"Se não a gente não sai daqui",
		"Verdade. Falamos depois",
		"Qualquer coisa me grita",
		"Pode deixar",
		"Ah, e não esquece o contato",
		"Do mecânico? Verdade",
		"Tô enviando agora",
		"Recebi aqui, valeu!",
		"Tomara que não seja nada grave",
		"Tomara. Depois te conto",
		"Beleza, boa sorte lá",
		"Valeu. Bom trabalho aí",
		"Pra nós",
		"Amém",
		"Até o almoço de amanhã",
		"Até! Não esquece",
		"Pode deixar, tá na agenda",
		"Abraço",
		"Falou!"
	},

	// Conversa 6: Compartilhando novidade
	{
		"Tenho uma novidade pra te contar!",
		"Conta aí, to curioso!",
		"Consegui aquilo que te falei!",
		"Sério? Parabéns! Muito feliz por você!",
		"Finalmente as chaves do apartamento saíram!",
		"Mentira! Já?",
		"Sim, me ligaram agora pouco da imobiliária",
		"Caraca, que rapidez foi essa?",
		"Nem eu acreditei quando vi o número chamando",
		"Nossa, que vitória hein",
		"Demais, tirei um peso das costas",
		"E quando você pega as chaves?",
		"Amanhã mesmo, na hora do almoço",
		"Aí sim! Já vai lá visitar?",
		"Com certeza, vou direto pra lá",
		"Manda foto de tudo depois",
		"Pode deixar, vou fazer um vídeo",
		"Já tem data pra mudança?",
		"Tô pensando no próximo sábado",
		"Sábado agora ou no outro?",
		"No outro, preciso organizar as caixas",
		"Ah sim, mudança é um caos",
		"Nem me fale, já tô com preguiça",
		"Hahaha imagino a zona que vai ficar",
		"Vou precisar de muita ajuda",
		"Opa, pode contar comigo",
		"Vou cobrar hein?",
		"Pode cobrar, ajudo a carregar caixa",
		"Você é o melhor, valeu mesmo",
		"Amigo é pra essas coisas",
		"Mas e aí, vai pintar antes?",
		"Vou sim, quero mudar a cor da sala",
		"Vai colocar que cor?",
		"Tô pensando num cinza claro",
		"Fica chique, moderno",
		"Pois é, combina com o sofá",
		"Você vai comprar sofá novo?",
		"Vou ter que comprar, o meu tá velho",
		"Aproveita as promoções",
		"Tô de olho num retrátil gigante",
		"Nossa, esses são os melhores",
		"Pra ver filme jogado no domingo",
		"Exatamente meu plano",
		"E a cozinha? Já tem tudo?",
		"Falta geladeira, a minha pifou",
		"Ixi, geladeira tá caro",
		"Tá um absurdo, tô chorando desconto",
		"Tenta comprar online, as vezes compensa",
		"Tô pesquisando em todo lugar",
		"Se achar oferta te mando",
		"Por favor, agradeço",
		"E o quarto? Vai manter a cama?",
		"Vou, a cama tá nova ainda",
		"Menos um gasto então",
		"Sim, graças a Deus",
		"Mas vou precisar de guarda-roupa",
		"Manda fazer planejado",
		"É o sonho, mas a grana tá curta",
		"Faz depois, com calma",
		"É, vou comprar um provisório",
		"Isso, ou usa arara por enquanto",
		"Estilo industrial né hahaha",
		"Hahaha isso, fala que é conceito",
		"Boa ideia, vou aderir",
		"E a vizinhança, parece tranquila?",
		"Parece que sim, rua sem saída",
		"Ah, então é silêncio total",
		"Espero que sim, odeio barulho",
		"Tem vaga de garagem?",
		"Tem uma, coberta",
		"Perfeito, seu carro agradece",
		"Nem fala, chega de deixar na rua",
		"Segurança em primeiro lugar",
		"Com certeza",
		"E o valor do condomínio?",
		"Até que é razoável pelo que oferece",
		"Tem piscina no prédio?",
		"Tem piscina e churrasqueira",
		"Opa! Já vi onde serão as festas",
		"Hahaha o Open House já tem local",
		"Com certeza, inauguração obrigatória",
		"Vamos marcar assim que eu arrumar tudo",
		"Sem pressa, arruma com calma",
		"Quero fazer um churrasco pra galera",
		"Eu levo a picanha",
		"Aí vi vantagem!",
		"E a cerveja deixa com a gente",
		"Fechado então",
		"Vai chamar muita gente?",
		"Só os mais chegados mesmo",
		"Melhor, evita bagunça demais",
		"Pois é, e vizinho reclamando",
		"Vizinho chato é o fim",
		"Já vou chegar fazendo média com eles",
		"Leva um bolo pro vizinho de porta",
		"Hahaha tática da boa vizinhança",
		"Funciona sempre",
		"Vou tentar, vai que cola",
		"Mas me diz, e o trabalho?",
		"Tá aquela loucura de sempre",
		"Conseguiu a folga pra mudança?",
		"Consegui negociar a sexta-feira",
		"Boa! Já adianta muita coisa",
		"Sim, pego a chave, ligo luz e água",
		"Essas burocracias são chatas",
		"Nossa, odeio essa parte",
		"Ficar ligando em 0800",
		"Ninguém merece musiquinha de espera",
		"Hahaha teste de paciência",
		"Total. Mas faz parte",
		"Sim, é por uma boa causa",
		"E seus pais, gostaram da novidade?",
		"Minha mãe chorou de emoção",
		"Que fofa! Mães são demais",
		"Meu pai já quis ver a planta",
		"Engenheiro né, quer ver a estrutura",
		"Exato, já perguntou da fiação",
		"Importante checar isso mesmo",
		"Ele vai lá comigo amanhã",
		"Ótimo, ele tem olho clínico",
		"Sim, não deixa passar nada",
		"Melhor consultoria impossível",
		"Economizei no vistoriador hahaha",
		"Tá certo!",
		"E você, como tá a semana?",
		"Tranquila, na medida do possível",
		"Projeto novo rolando?",
		"Tem um entrando semana que vem",
		"Vai ficar atarefado então",
		"Vou, mas é dinheiro extra",
		"Sempre bem-vindo",
		"Ainda mais agora que vou gastar",
		"Verdade, mudança suga o dinheiro",
		"Cada dia aparece uma taxa nova",
		"É cartório, é frete, é tinta...",
		"Nem me lembre, choro no banho",
		"Hahaha rir pra não chorar",
		"Mas vai valer a pena",
		"Vai sim, seu cantinho",
		"Liberdade não tem preço",
		"Poder andar de cueca na sala",
		"Hahaha exatamente!",
		"Ouvir música alta",
		"Bom, nem tanto pra não levar multa",
		"Verdade, tem as regras",
		"Vou ler o regimento interno",
		"Lê mesmo pra não ter surpresa",
		"Tem prédio que é chato com pet",
		"Você vai levar o cachorro?",
		"Vou né, ele é meu filho",
		"Ele vai estranhar no começo",
		"Vai, tadinho. Vou ter que telar tudo",
		"Ah é, segurança pra ele",
		"Tela nas janelas e na sacada",
		"Primeira coisa a fazer",
		"Já cotei o preço, tá na média",
		"Isso não dá pra economizar",
		"Jamais, fico sem sofá mas não sem tela",
		"Prioridades certas",
		"E a internet? Já pediu transferência?",
		"Putz! Bem lembrado!",
		"Liga lá agora, demoram pra instalar",
		"Vou ligar assim que desligar aqui",
		"Se ficar sem net, você surta",
		"Trabalho home office, não posso ficar sem",
		"Então corre",
		"Caraca, minha cabeça tá a mil",
		"Normal, é muita coisa pra pensar",
		"Tô fazendo uma lista no papel",
		"Melhor coisa, vai ticando",
		"Isso dá uma satisfação",
		"Ver a lista diminuindo",
		"Sim! Sensação de dever cumprido",
		"Você precisa de caixas de papelão?",
		"Preciso! Onde eu arrumo?",
		"Tenho umas no escritório, posso pegar",
		"Sério? Me salva muito",
		"Vou separar pra você hoje",
		"Valeu demais!",
		"Passo aí pra pegar quando?",
		"Pode ser amanhã fim de tarde",
		"Combinado, passo aí",
		"Traz o carro que é volume",
		"Beleza, vou de mala vazia",
		"Jornal velho também ajuda",
		"Pra embrulhar copo né?",
		"Isso, e prato também",
		"Vou ver se acho aqui",
		"Pede na portaria, eles guardam",
		"Boa ideia, vou falar com o porteiro",
		"Seu Zé deve ter",
		"Ele guarda tudo hahaha",
		"Figuraça ele",
		"Vou sentir falta das resenhas",
		"Ah, mas você volta pra visitar",
		"Volto sim, meus pais ficam lá",
		"Então tá tranquilo",
		"E o futebol de quarta?",
		"Essa semana eu furo",
		"Imaginava, foco na mudança",
		"Semana que vem eu volto",
		"Beleza, aviso a galera",
		"Diz que tô no departamento médico",
		"Lesão: carregamento de sofá",
		"Hahaha boa, tendinite de empacotamento",
		"Essa é clássica",
		"Bom, deixa eu ir lá ligar na net",
		"Vai lá, não perde tempo",
		"Depois te conto se deu certo",
		"Beleza, fico no aguardo",
		"Obrigado por ouvir meu surto",
		"Que isso, tamo junto",
		"Qualquer coisa grita",
		"Pode deixar",
		"Ah, antes que eu esqueça",
		"Diga?",
		"Viu o jogo ontem?",
		"Vi nada, dormi cedo",
		"Perdeu, foi 3 a 0",
		"Mentira? Goleada?",
		"Amassaram o outro time",
		"Caramba, preciso ver os gols",
		"Vê lá, golaço do camisa 10",
		"Esse mlk joga muito",
		"Joga fácil",
		"Só não joga mais que o Isaque",
		"Ah sim, o melhor da Copa",
		"Sim, menos quando ele se perde nos bares kkkk",
		"Sério, qual bar?",
		"Aquele tal de terraria, já ouviu falar?",
		"Ah sim, já ouvi falar um pouco",
		"É muito bom, recomendo",
		"Agora fui mesmo",
		"Vai lá resolver a vida",
		"Abraço mano",
		"Abraço, parabéns de novo",
		"Valeu!",
		"Falou",
		"👋",
		"🏠",
		"🔑"
	},

	// Conversa 7: Pedindo opinião
	{
		"Preciso da sua opinião sobre uma coisa",
		"Claro, pode falar",
		"Depois te mando os detalhes, pode ser?",
		"Tranquilo, fico no aguardo",
		"Tô entrando numa reunião agora",
		"Putz, aquelas intermináveis?",
		"Exato, o chefe tá daquele jeito",
		"Boa sorte aí, guerreiro",
		"Vou precisar, valeu",
		"Quando sair me dá um toque",
		"Pode deixar",
		"...",
		"E aí, sobreviveu?",
		"Cara, quase dormi lá dentro",
		"Hahaha imagino a tortura",
		"Foi só lero lero e nada resolvido",
		"Clássico de reuniões corporativas",
		"Perdi duas horas de vida",
		"Pelo menos tem ar condicionado",
		"É o único consolo",
		"Mas e aí, qual era o assunto?",
		"Então, tô querendo comprar um relógio",
		"Opa, relógio é comigo mesmo",
		"Eu sei, por isso te chamei",
		"Tá em dúvida entre quais?",
		"Tô entre um smartwatch e um clássico",
		"Dúvida cruel essa",
		"Pois é, estilos bem diferentes",
		"Depende do uso, mano",
		"Então, eu quero pra usar no dia a dia",
		"O smart é bom pra notificação",
		"Sim, e pra academia também",
		"Verdade, monitora tudo",
		"Mas o clássico tem presença, né?",
		"Nossa, nem se compara",
		"Um de couro fica chique demais",
		"Fica outra naipe",
		"Vi um modelo preto fosco",
		"Sério? Manda foto se tiver",
		"Vou mandar o link, peraí",
		"[Link enviado]",
		"Caraca, bonitão hein",
		"Né? Achei muito estiloso",
		"E o preço? Tá salgado?",
		"Tá um pouco acima do que eu queria",
		"Mas relógio bom é investimento",
		"Também penso assim",
		"Dura a vida toda se cuidar",
		"Exato. Agora olha o smart",
		"[Link enviado]",
		"Esse é o último modelo?",
		"É sim, lançou mês passado",
		"Bateria dura quanto tempo?",
		"Dizem que uns dois dias",
		"Ah, isso que me quebra",
		"Ter que carregar relógio é chato",
		"Pois é, mais um cabo pra levar",
		"O clássico é só por no pulso e ir",
		"Tô pendendo pro clássico mesmo",
		"Eu iria nele, sem dúvidas",
		"Combina mais com roupa social",
		"Sim, e você trabalha de camisa",
		"Exatamente",
		"O smart fica meio esporte demais",
		"Às vezes fica parecendo brinquedo",
		"Hahaha verdade",
		"Mas as funções de saúde são legais",
		"São, mas você vai usar mesmo?",
		"No começo sim, depois esqueço",
		"Então pronto, tá respondido",
		"Você tem um ponto",
		"Vai no clássico que é sucesso",
		"E aquele site é confiável?",
		"Aquele do link? É sim",
		"Já comprou lá?",
		"Já comprei um perfume lá",
		"Chegou certinho?",
		"Chegou rápido até",
		"Beleza, vou boletar então",
		"Parcela no cartão que dói menos",
		"Vou fazer em 10x sem juros",
		"Aí sim, nem sente a parcela",
		"Hahaha sente sim, mas finge que não",
		"O importante é estar estiloso",
		"Vou ficar parecendo empresário",
		"Só falta a lancha agora",
		"A lancha vem em 2050",
		"Sonhar não custa nada",
		"Mudando de assunto, viu o Pedro?",
		"Não, sumiu aquele lá",
		"Tá namorando, esqueceu dos amigos",
		"Ah, tá explicado então",
		"Gado demais",
		"Sempre foi, desde a escola",
		"Hahaha não muda nunca",
		"Vamos marcar algo pra resgatar ele",
		"Bora, um churrasco no sábado?",
		"Pode ser lá em casa",
		"Show, eu levo a carne",
		"Eu compro a bebida",
		"Chama o Lucas também",
		"O Lucas tá viajando a trabalho",
		"Sério? Pra onde?",
		"Tá lá no sul, frio danado",
		"Corajoso, odeio frio",
		"Eu gosto, mas prefiro praia",
		"Praia é vida",
		"Falando nisso, feriado tá aí",
		"Vai viajar?",
		"Tô sem grana agora",
		"Gastou tudo no relógio né",
		"Hahaha me descobriu",
		"Prioridades, amigo",
		"Vou ficar por aqui mesmo",
		"A gente faz algo por aqui",
		"Tem aquele bar novo que abriu",
		"Onde? No centro?",
		"Não, na avenida principal",
		"Ah, vi a fachada, parece top",
		"Dizem que o petisco é bom",
		"Se tem comida boa eu vou",
		"Hahaha gordo pensa com o estômago",
		"Sempre! É a lei",
		"Podemos ir na sexta à noite",
		"Sexta feira é sagrado",
		"Happy hour da firma",
		"Isso, sai do trabalho e vai",
		"Fechado então",
		"Vou avisar a patroa",
		"Ela vai junto?",
		"Acho que sim, ela curte barzinho",
		"Beleza, levo a minha também",
		"Vira encontro de casais",
		"Hahaha que fase a nossa",
		"Ficamos velhos, mano",
		"Velhos não, experientes",
		"Isso aí, gostei",
		"Lembra quando a gente virava noite?",
		"Nossa, balada até amanhecer",
		"Hoje se eu viro, morro no dia seguinte",
		"Preciso de 3 dias pra recuperar",
		"A ressaca dura uma semana",
		"O fígado pede arrego",
		"Triste realidade",
		"Mas a gente aproveitou bem",
		"Muito! Histórias pra contar não faltam",
		"Aquela viagem pra Cabo Frio...",
		"Nem me lembre! O carro quebrou",
		"No meio da serra, de madrugada",
		"E a gente rindo de nervoso",
		"Hahaha foi perrengue chique",
		"Ainda bem que passou",
		"Hoje dou risada, na hora queria chorar",
		"Com certeza",
		"Ei, voltando ao relógio",
		"Pode falar",
		"Tem na cor prata também",
		"Hum, prata é clássico",
		"Mas o preto chama mais atenção",
		"O preto é mais moderno",
		"O prata é mais tiozão?",
		"Um pouco, depende do modelo",
		"Vou ficar no preto mesmo",
		"Decisão sábia",
		"Combina com tudo",
		"Até com roupa de academia se duvidar",
		"Não força a amizade",
		"Hahaha tô zoando",
		"Chegou e-mail aqui, droga",
		"Lá vem bomba",
		"Cliente pedindo alteração",
		"Sempre de última hora",
		"Eles acham que é pastel",
		"Frita aí rapidinho",
		"Dá uma raiva disso",
		"Respira fundo e vai",
		"Vou ter que abrir o Photoshop",
		"Força aí no design",
		"Vou demorar hoje pelo jeito",
		"Vai pedir hora extra?",
		"Banco de horas, infelizmente",
		"Melhor que nada",
		"Pelo menos folgo depois",
		"Isso se o chefe deixar",
		"Ele é tranquilo com isso",
		"Menos mal",
		"Bom, vou focar aqui senão não saio",
		"Vai lá, bom trampo",
		"Valeu pela ajuda na escolha",
		"Tamo junto, precisando grita",
		"Depois mando foto quando chegar",
		"Manda sim, quero ver no pulso",
		"Se ficar feio eu devolvo",
		"Tem 7 dias pra arrepender",
		"Verdade, direito do consumidor",
		"Mas vai ficar top, confia",
		"Tomara",
		"Ah, e o churrasco?",
		"De pé?",
		"De pé! Sábado à tarde",
		"Beleza, vou comprar carvão",
		"Eu levo aquela farofa pronta",
		"Aquela picante?",
		"Essa mesma, a melhor",
		"Nossa, deu água na boca",
		"Você leva a picanha hein",
		"Pode deixar, carne de primeira",
		"Nada de carne dura",
		"Respeita meu churrasco",
		"Hahaha tô ligado que você manda bem",
		"Modéstia à parte, sou bom assador",
		"Veremos no sábado",
		"Desafio aceito",
		"Vou levar meu violão",
		"Aí sim, música ao vivo",
		"Mas só sei tocar Legião",
		"Tá ótimo, clássico é clássico",
		"Vamos cantar Faroeste Caboclo inteira",
		"Hahaha haja voz e cerveja",
		"9 minutos de música",
		"Ninguém aguenta",
		"Mas a gente tenta",
		"Beleza então mano",
		"Vou nessa aqui",
		"Vai lá produzir",
		"Mais tarde a gente se fala",
		"Se eu não responder, tô na casa do Bruno",
		"Calma, o Bruno Brandão?",
		"Sim, o primo do Jarbas",
		"Achei que ele estava morando em outra cidade",
		"Ele estava mas acabou voltando pra cá semana passada",
		"O que aconteceu?",
		"Nada demais, só quis ficar perto da familia novamente",
		"Que bom, ele é muito legal",
		"Bastante, pode passar por lá se quiser",
		"Tranquilo, vou ver se posso",
		"Beleza mano",
		"Valeu!",
		"Abraço",
		"Falou",
		"Tchau"
	},

	// Conversa 8: Lembrando de algo
	{
		"Lembrei de você hoje!",
		"Que legal! Por quê?",
		"Vi algo que você ia gostar",
		"Ah que bacana! Mostra depois!",
		"Vou te mandar o link agora",
		"Espera aí",
		"Tá bom, tô curiosa",
		"É sobre aquela série que a gente falou",
		"Mentira! Saiu trailer novo?",
		"Não, melhor ainda",
		"É uma promoção dos livros de capa dura",
		"Nossa, sério??",
		"Sério! Tão com 50% de desconto",
		"Manda o link PELO AMOR DE DEUS",
		"Calma, tô procurando aqui",
		"Achou?",
		"Achei! Segue o link:",
		"[Link enviado]",
		"Nossa, que lindo!",
		"Eu disse que você ia gostar",
		"Mano, o box completo tá muito barato",
		"Né? Eu quase comprei dois",
		"Vou comprar agora mesmo",
		"Faz isso antes que acabe",
		"Já coloquei no carrinho",
		"Boa!",
		"E aí, como tão as coisas?",
		"Tudo indo, na correria de sempre",
		"Imagino, e o trabalho?",
		"Cansativo, mas tamo aí",
		"E você?",
		"Ah, tá tranquilo",
		"Tô de férias essa semana",
		"Que inveja branca",
		"Hahaha, precisava muito",
		"Vai viajar?",
		"Acho que não, só descansar mesmo",
		"Justo",
		"Tem que aproveitar pra dormir",
		"Exatamente isso que vou fazer",
		"E colocar as séries em dia",
		"Com certeza!",
		"Terminou aquela lá?",
		"Ainda não, tô no episódio 5",
		"Menina, o final do 6 é chocante",
		"Não me dá spoiler!",
		"Jamais faria isso",
		"Bom mesmo",
		"Mas prepara o coração",
		"Ai meu Deus, tô com medo",
		"Relaxa, é bom",
		"Se você diz...",
		"Mudando de assunto",
		"Diga",
		"Viu o que aconteceu com o Lucas?",
		"Não! O que houve?",
		"Ele mudou de cidade",
		"Mentira!",
		"Sério, foi pra São Paulo",
		"Do nada assim?",
		"Pois é, recebeu uma proposta de emprego",
		"Caramba, que coragem",
		"Né? Eu não iria assim tão rápido",
		"Nem eu",
		"Mas espero que dê certo pra ele",
		"Sim, ele merece",
		"Vamos marcar algo antes dele ir?",
		"Ele já foi!",
		"Jura? Nem se despediu?",
		"Foi super corrido parece",
		"Poxa, que pena",
		"Pois é",
		"Mas a gente devia marcar algo nós dois",
		"Verdade! Faz tempo",
		"Bora nesse fim de semana?",
		"Sábado rola?",
		"Sábado à tarde eu posso",
		"Fechado então",
		"Onde a gente vai?",
		"Podia ser naquele café novo",
		"Aquele do centro?",
		"Isso, dizem que o bolo é ótimo",
		"Hummm, deu vontade",
		"Então tá combinado",
		"Beleza",
		"Que horas?",
		"Umas 15h?",
		"Pode ser 15:30?",
		"Pode sim",
		"Show",
		"Vou ver se a Mari quer ir também",
		"Chama ela sim",
		"Faz séculos que não vejo a Mari",
		"Ela tá namorando, sabia?",
		"Sério? Com quem?",
		"Um rapaz do trabalho dela",
		"Ah, que legal",
		"Parece gente boa",
		"Tomara que ela vá",
		"Vou mandar msg pra ela agora",
		"Tá bom",
		"Depois me avisa",
		"Pode deixar",
		"E seu cachorro? Melhorou?",
		"Melhorou sim, graças a Deus",
		"Que bom",
		"Era só uma alergia mesmo",
		"Menos mal",
		"Gastei uma nota no vet",
		"Imagino, é tudo caro",
		"Mas ele vale a pena",
		"Com certeza, é um fofo",
		"Ontem ele comeu meu chinelo",
		"KKKKKKKKKK",
		"Ria não, foi trágico",
		"Desculpa, mas imaginei a cena",
		"Ele com cara de culpado depois",
		"Clássico",
		"Tira uma foto dele pra mim",
		"Peraí",
		"[Foto enviada]",
		"Awnnnnn que coisinha linda",
		"Linda e destruidora",
		"Hahaha, faz parte",
		"Olha, a Mari respondeu",
		"O que ela disse?",
		"Disse que vai!",
		"Aeee, top",
		"Vai ser legal",
		"Vai sim",
		"Tô precisando sair de casa",
		"Eu também, tô mofando aqui",
		"Kkkkkk",
		"Vida de adulto não é fácil",
		"Não mesmo",
		"Saudades da escola",
		"Nossa, nem me fale",
		"A única preocupação era a prova de matemática",
		"E o recreio",
		"Simmm, o lanche",
		"Coxinha da cantina",
		"Nossa, a melhor",
		"Nunca mais comi uma igual",
		"Nem eu",
		"Deu fome agora",
		"Somos dois",
		"Vou ver o que tem na geladeira",
		"Vai lá",
		"Voltei",
		"O que achou?",
		"Nada de bom",
		"Triste",
		"Vou ter que pedir algo",
		"Pede uma pizza",
		"Tô pensando nisso",
		"Meio a meio?",
		"Sempre",
		"Calabresa e Frango com Catupiry",
		"Clássico que nunca falha",
		"Deu água na boca",
		"Pede aí também",
		"Tô de dieta :(",
		"Ah é, esqueci",
		"Pois é, sofrendo aqui",
		"Força guerreira",
		"Comendo salada e chorando",
		"Hahahaha",
		"No sábado você chuta o balde",
		"Com certeza",
		"Vou comer aquele bolo inteiro",
		"Isso aí",
		"O bolo de cenoura com chocolate de lá é divino",
		"Para, senão eu vou aí agora",
		"Pareiiiii",
		"Mudei de assunto",
		"Viu aquele meme do gato?",
		"Qual deles? Tem mil",
		"Aquele dançando",
		"Acho que não",
		"Vou te mandar",
		"[Sticker enviado]",
		"KKKKKKKKKKKKKK",
		"Muito bom né?",
		"A cara dele é a melhor",
		"Eu na vida",
		"Totalmente",
		"Vou salvar essa figurinha",
		"Rouba aí",
		"Já roubei",
		"Tenho várias novas",
		"Manda as melhores",
		"[Sticker enviado]",
		"[Sticker enviado]",
		"[Sticker enviado]",
		"Mano kkkkkk",
		"Essa do Bob Esponja é ótima",
		"Uso pra tudo",
		"Vou usar no grupo da família",
		"Cuidado hein",
		"Minha tia não vai entender nada",
		"Vai achar que é vírus",
		"Exatamente kkkkk",
		"Ai ai...",
		"Mas e aí, comprou o livro?",
		"Comprei!",
		"Aprovado o pagamento?",
		"Sim, chega em 3 dias",
		"Rapidão",
		"Amo entrega rápida",
		"Ansiedade agradece",
		"Muito",
		"Quando chegar eu posto foto",
		"Me marca",
		"Pode deixar",
		"Agora vou ter que ler tudo de novo",
		"Vai valer a pena",
		"A edição tá linda demais",
		"Tô pensando em comprar um pra mim também",
		"Compra logo",
		"Vou ver se sobrou limite no cartão",
		"O drama do brasileiro",
		"Sempre no limite",
		"Literalmente",
		"Kkkkkk chorindo",
		"Enfim",
		"Vou pedir minha pizza aqui",
		"Vai lá, mata a fome",
		"Depois a gente se fala mais",
		"Beleza",
		"Não esquece de sábado",
		"Jamais",
		"Já tá na agenda",
		"15:30 lá na frente",
		"Isso",
		"Se eu atrasar, me espera",
		"Você sempre atrasa",
		"Ei! Injustiça",
		"Tô brincando",
		"Mas chega na hora",
		"Tá bom, prometo",
		"Vou tentar não me perder",
	},

	// Conversa 9: Check-in rápido
	{
		"Só passando pra dar um oi",
		"Opa! Que bom te ouvir!",
		"Tava com saudade de trocar ideia",
		"Também! Vamos nos falar mais",
		"Como você tá?",
		"Tô bem, e você?",
		"Tô levando, correria de sempre",
		"Imagino, trabalho tá puxado?",
		"Nossa, nem me fale",
		"Muita demanda essa semana",
		"Aqui também tá uma loucura",
		"Sério? O que tá rolando?",
		"Chefe novo, sabe como é",
		"Ixi, quer mostrar serviço",
		"Exatamente isso",
		"Ninguém merece",
		"Mas e as novidades?",
		"Ah, mudei de apartamento!",
		"Mentira! Pra onde?",
		"Fui pro centro agora",
		"Que chique!",
		"Fica perto de tudo né",
		"Sim, facilitou minha vida",
		"E o aluguel? Caro?",
		"Um pouco, mas compensa",
		"Economizo no transporte",
		"Verdade, tem que botar na ponta do lápis",
		"E você, continua no mesmo lugar?",
		"Continuo...",
		"Tô querendo mudar ano que vem",
		"Faz bem, renovar as energias",
		"Pois é",
		"Mas me diz, e o coração?",
		"Hahahaha",
		"Essa pergunta não pode faltar",
		"Tá gelado, pedra de gelo",
		"Duvido muito",
		"Sério! Tô focado em mim",
		"Arrasou, é o melhor a fazer",
		"E o seu?",
		"Ah, tá enrolado",
		"Sempre tá né?",
		"Kkkkk me respeita",
		"Mas tem alguém interessante?",
		"Tem um crush aí...",
		"Conta tudo!",
		"Depois te conto os detalhes",
		"Ah não, odeio suspense",
		"É que é complicado",
		"Entendi, segredo de estado",
		"Tipo isso",
		"Mudando de assunto",
		"Viu que vai ter show na cidade?",
		"Vi! Do Jorge e Mateus?",
		"Isso mesmo",
		"Você vai?",
		"Tô pensando hein",
		"A gente podia ir",
		"Bora! Eu animo",
		"Vou ver quanto tá o ingresso",
		"Vê aí e me fala",
		"Deve estar caro",
		"Com certeza, lote virou ontem",
		"Aff, que azar",
		"Mas a gente parcela",
		"Deus abençoe o cartão de crédito",
		"Amém kkkkk",
		"Vou chamar a galera",
		"Isso, quanto mais gente melhor",
		"A Ju tava querendo ir",
		"Faz tempo que não vejo a Ju",
		"Ela tá ótima, pintou o cabelo",
		"Ficou loira?",
		"Ficou ruiva!",
		"Nossa, deve ter ficado lindo",
		"Ficou sim, combinou muito",
		"Vou mandar msg pra ela depois",
		"Manda sim",
		"E esse fim de semana agora?",
		"Vou ficar de boa",
		"Netflix e pipoca?",
		"Basicamente isso",
		"Tô precisando descansar",
		"Eu também, tô moída",
		"Mas sábado tem churrasco",
		"Onde?",
		"Na casa do Pedro",
		"Ah, verdade, aniversário dele",
		"Você vai né?",
		"Acho que vou dar uma passada",
		"Tem que ir!",
		"Vou levar um refrigerante",
		"Leva aquele bolo que você faz",
		"Menina, tô sem tempo de cozinhar",
		"Que pena, amo teu bolo",
		"Comprei na padaria mesmo",
		"Tá valendo também",
		"O importante é comer",
		"Falando em comer...",
		"Lá vem",
		"Tô com uma fome monstra",
		"Almoçou o que?",
		"Salada",
		"Só salada? Tá doido?",
		"Dieta, né",
		"Nossa, eu não aguento",
		"Tô quase desistindo",
		"Come um chocolatinho",
		"Não me tenta!",
		"Um só não mata",
		"Se eu comer um, como a caixa",
		"Te entendo perfeitamente",
		"Sou viciado em doce",
		"Eu sou mais do salgado",
		"Uma coxinha agora...",
		"Nossa, nem fala",
		"Com catupiry",
		"Para que é tortura",
		"Kkkkkk parei",
		"Viu a série nova da HBO?",
		"The Last of Us?",
		"Essa mesmo",
		"Ainda não comecei",
		"Começa logo!",
		"É boa mesmo?",
		"É perfeita",
		"Chorei no primeiro ep",
		"Ai, sou chorona",
		"Então prepara o lenço",
		"Vou ver hoje à noite",
		"Depois me conta o que achou",
		"Pode deixar",
		"Tô maratonando Friends de novo",
		"Pela milésima vez?",
		"Sim, conforto emocional",
		"Te entendo, faço isso com The Office",
		"The Office é genial",
		"Melhor série de comédia",
		"Concordo plenamente",
		"Dwight é o melhor",
		"Sem dúvidas kkkkk",
		"Ei, lembra do Marcos?",
		"Da faculdade?",
		"Isso",
		"Lembro, o que tem ele?",
		"Casou!",
		"Mentira??",
		"Sério, vi no Insta",
		"Caramba, ele era mó festeiro",
		"O mundo gira, né?",
		"E a gente aqui",
		"Solteiros e felizes",
		"Kkkkk rindo de nervoso",
		"Mas ele parece feliz",
		"Que bom pra ele",
		"A festa parecia linda",
		"Imagino",
		"Fiquei com vontade de ir em casamento",
		"Só pra comer bem casados?",
		"Me descobriu",
		"Melhor parte da festa",
		"Isso e o open bar",
		"Com certeza",
		"Nossa, começou a chover aqui",
		"Aqui também",
		"Caiu o mundo do nada",
		"Esqueci a janela aberta!",
		"Corre lá!",
		"Voltei",
		"Molhou tudo?",
		"Só um pouco o sofá",
		"Menos mal",
		"Tempo doido",
		"Pois é, tava sol agorinha",
		"Mudanças climáticas",
		"Assustador",
		"Mas enfim, refrescou",
		"Verdade, tava muito calor",
		"Dormir com barulho de chuva é vida",
		"Melhor coisa que existe",
		"Hoje eu apago cedo",
		"Eu também preciso",
		"Amanhã acordo cedo",
		"Vai pra academia?",
		"Vou tentar né",
		"Guerreiro",
		"Tô pagando de otário, não vou nunca",
		"Kkkkkk clássico",
		"Doa o dinheiro pra mim então",
		"Vou cancelar esse mês",
		"Promessa de ano novo falhou",
		"Totalmente",
		"Quem sabe mês que vem",
		"A esperança é a última que morre",
		"Exato",
		"Escuta, tá sabendo da fofoca?",
		"Qual? Adoro fofoca",
		"A vizinha aqui do lado",
		"O que ela fez?",
		"Arrumou briga no grupo do condomínio",
		"Por causa de que?",
		"Cachorro latindo",
		"Ah, sempre isso",
		"Mas ela fez um escândalo",
		"Mandou áudio gritando?",
		"Sim! 5 minutos de áudio",
		"Manda pra mim",
		"Vou encaminhar",
		"Espera aí",
		"MEU DEUS",
		"Ela tá descontrolada",
		"Eu ri muito ouvindo",
		"Coitado do síndico",
		"Ninguém mandou ser síndico",
		"Verdade, pepino puro",
		"Eu jamais aceitaria",
		"Nem eu, Deus me livre",
		"Prefiro minha paz",
		"Mas e aí, vamos marcar aquele café?",
		"Vamos sim, com certeza",
		"Semana que vem pode ser?",
		"Pode, terça é bom pra você?",
		"Terça à noite?",
		"Isso, depois do trabalho",
		"Perfeito",
		"Combinado então",
		"A gente confirma o lugar depois",
		"Beleza",
		"Agora vou ter que sair",
		"Vai lá",
		"Chefe tá chamando aqui",
		"Boa sorte aí",
		"Valeu, vou precisar",
		"Depois a gente continua",
		"Isso, não some não",
		"Pode deixar",
		"Adorei conversar contigo",
		"Eu também!",
		"Tava fazendo falta",
		"Muita",
		"Beijão",
	},

	// Conversa 10: Combinando retorno
	{
		"Conseguiu resolver aquele assunto?",
		"Ainda não, mas to quase lá",
		"Qualquer coisa me avisa que ajudo",
		"Valeu! Te dou um retorno em breve",
		"Tá travado naquela parte do login?",
		"Isso mesmo, diz que a senha tá errada",
		"Mas você não tinha trocado ontem?",
		"Troquei! Tenho certeza absoluta",
		"Tenta o 'esqueci minha senha' de novo",
		"Já tentei 3 vezes",
		"E o que acontece?",
		"O e-mail de recuperação não chega",
		"Vixeee",
		"Olhou na caixa de spam?",
		"Olhei, nada também",
		"Que sistema bugado hein",
		"Nem me fale, tô sem paciência já",
		"Quer que eu tente daqui?",
		"Acho que não vai adiantar",
		"Mas não custa tentar né",
		"Beleza, tenta aí",
		"Me manda o usuário",
		"É o meu e-mail pessoal",
		"Tá, vou testar aqui",
		"Enquanto isso vou pegar um café",
		"Vai lá",
		"Voltei",
		"E aí?",
		"Aqui deu usuário não encontrado",
		"Mentira??",
		"Sério, tirei até print",
		"Mano, como assim?",
		"Será que deletaram tua conta?",
		"Não é possível",
		"Eu usei ela ontem a noite",
		"Muito estranho",
		"Vou ter que ligar no suporte",
		"Boa sorte, vai precisar",
		"Aquela musiquinha de espera é tortura",
		"Kkkkkk nem me lembre",
		"Vou colocar no viva voz",
		"Isso, e vai fazendo outra coisa",
		"Vou adiantar aquele relatório",
		"Boa",
		"E por falar em relatório...",
		"Lá vem",
		"Você terminou o seu?",
		"Terminei ontem de madrugada",
		"Guerreiro demais",
		"Tava atrasado, não tive escolha",
		"O chefe cobrou?",
		"Cobrou hoje cedo",
		"Ainda bem que entregou",
		"Pois é, me livrei",
		"E o fim de semana?",
		"Foi tranquilo, e o seu?",
		"Fiquei em casa jogando",
		"Jogou o que?",
		"Aquele RPG novo",
		"É bom mesmo?",
		"Cara, é viciante",
		"Os gráficos são surreais",
		"Tô pensando em baixar",
		"Baixa, a gente joga junto",
		"Meu PC não deve rodar",
		"Roda sim, é bem otimizado",
		"Vou testar depois",
		"Faz isso",
		"Ei, o suporte atendeu!",
		"Aleluia",
		"Espera aí que vou falar com a moça",
		"Tá, muta aí",
		"Beleza",
		"Pronto, desliguei",
		"Resolveu?",
		"Disseram que é instabilidade no servidor",
		"Ah, a velha desculpa",
		"Pois é, clássico",
		"Deram prazo?",
		"Disseram 'em algumas horas'",
		"Ou seja, só amanhã",
		"Provavelmente",
		"Aff, que atraso de vida",
		"Vou largar isso de mão por agora",
		"Melhor coisa que você faz",
		"Vamo falar de coisa boa",
		"Comida?",
		"Sempre kkkkk",
		"Tô com uma fome de leão",
		"Já são 12:30 né",
		"Bora almoçar onde?",
		"Aquele self-service da esquina?",
		"Enjoei de lá",
		"Tem o de massas também",
		"Hummm, macarrão cai bem",
		"Com bastante queijo",
		"Nossa, sim",
		"Bora então?",
		"Bora, passo aí em 10 min",
		"Fechado",
		"Traz o guarda-chuva",
		"Tá chovendo?",
		"Tá armando um temporal",
		"Vixe, valeu pelo aviso",
		"O céu tá preto aqui",
		"Vou levar o casaco também",
		"Leva que vai esfriar",
		"Beleza",
		"Viu a foto que a Carol postou?",
		"Não, tô sem Instagram no celular",
		"Desinstalou?",
		"Sim, tava viciado demais",
		"Te entendo, toma muito tempo",
		"Mas o que ela postou?",
		"Tá em Paris a bonida",
		"Rycaaaa",
		"Quem pode, pode né",
		"E a gente aqui trabalhando",
		"A vida não é justa kkkk",
		"Um dia a gente chega lá",
		"Fé no pai",
		"Mas ela mereceu, trabalhou muito",
		"Isso é verdade",
		"Juntou grana o ano todo",
		"Tem que ter foco",
		"Coisa que eu não tenho",
		"Nem eu",
		"Gasto tudo em lanche",
		"Eu gasto com jogo",
		"Prioridades né kkkk",
		"Exatamente",
		"Opa, pingou uma notificação aqui",
		"Do sistema?",
		"Sim! Voltou!",
		"Mentira, já?",
		"Acho que era mentira do suporte",
		"Tava só reiniciando o modem deles",
		"Certeza kkkkkk",
		"Tenta logar aí",
		"Vou tentar agora",
		"Digitando a senha...",
		"E aí???",
		"ENTROUUUU",
		"Aeeee caramba",
		"Glória a Deus",
		"Agora resolve logo isso",
		"Vou fazer agora mesmo",
		"Antes que caia de novo",
		"Bem lembrado",
		"Corre",
		"Tô preenchendo o formulário",
		"Cuidado pra não errar",
		"Tô conferindo tudo",
		"CPF ok",
		"Endereço ok",
		"Data de nascimento ok",
		"Manda bala",
		"Botão de enviar...",
		"Clicou?",
		"Carregando...",
		"Que tensão",
		"Foi! Sucesso!",
		"Boa! Menos um problema",
		"Nossa, que alívio",
		"Tirei um peso das costas",
		"Agora o almoço vai descer melhor",
		"Com certeza",
		"Vou até pedir sobremesa",
		"Merecido",
		"Vou descer, tá pronto?",
		"Tô calçando o tênis",
		"Vai logo",
		"Tô indo, calma",
		"O elevador tá demorando",
		"Vai de escada preguiçoso",
		"10 andares? Nem a pau",
		"Faz cardio",
		"Hoje não kkkkk",
		"Chegou o elevador",
		"Tá, tô te esperando na portaria",
		"Beleza, tô descendo",
		"Ah, traz minha caneta?",
		"Qual delas?",
		"A azul que esqueci aí",
		"Tá na minha mesa?",
		"Acho que sim",
		"Peraí que vou voltar pra pegar",
		"Não! Se já tá no elevador deixa",
		"Já saí, tô pegando",
		"Você é muito bonzinho",
		"Sou um anjo, eu sei",
		"Convencido",
		"Achei a caneta",
		"Show, valeu",
		"Agora tô descendo de verdade",
		"Tá chovendo já?",
		"Começou a respingar",
		"Corre então",
		"Tô indo",
		"Cheguei no térreo",
		"Tô te vendo",
		"Onde?",
		"Aqui perto da banca",
		"Ah, vi",
		"Bora que a fome tá negra",
		"Partiu",
		"Depois a gente vê aquele outro negócio",
		"Que outro negócio?",
		"Do projeto do site",
		"Ah é, tinha esquecido",
		"Mas deixa pra tarde",
		"Isso, cabeça cheia agora",
		"Agora é hora do rango",
		"Isso aí",
		"E aí, vai querer o que de bebida?",
		"Coca com gelo e limão",
		"Perfeito",
		"Hoje eu não conto calorias",
		"Nem eu",
		"Amanhã a gente corre atrás",
		"Literalmente",
		"Kkkkkk",
		"Chegamos",
		"Tá cheia a fila",
		"Normal pra esse horário",
		"Mas anda rápido",
		"Espero",
		"Olha ali o Carlos",
		"Onde?",
		"Na mesa do canto",
		"Nossa, ele emagreceu hein",
		"Fez bariátrica",
		"Ah, tá explicado",
		"Ficou bem",
		"Sim, outra pessoa",
		"Vamos sentar ali perto?",
		"Pode ser",
		"Dá pra dar um oi",
		"Isso",
		"Pegou o prato?",
		"Peguei",
	},
}
